version: 2

.x-cockroach-19.2: &cockroach-19-2
  image: cockroachdb/cockroach:v19.2.12
  command: start-single-node --insecure

.x-cockroach-20.1: &cockroach-20-1
  image: cockroachdb/cockroach:v20.1.17
  command: start-single-node --insecure

.x-cockroach-20.2: &cockroach-20-2
  image: cockroachdb/cockroach:v20.2.11
  command: start-single-node --insecure

.x-cockroach-21.1: &cockroach-21-1
  image: cockroachdb/cockroach:v21.1.2
  command: start-single-node --insecure

.x-tox-version: &tox-version
  TOX_VERSION: 3.23.1

.x-py39: &py39
  environment:
    TOXENV: py39
    <<: *tox-version

.x-test-steps: &test-steps
  steps:
    - checkout
    - run:
        name: Wait for database
        command: dockerize -wait tcp://127.0.0.1:26257 -timeout 120s
    - run:
        name: Install testrunner
        command: pip install --user tox==${TOX_VERSION}
    - run:
        name: Test
        command: ${HOME}/.local/bin/tox

jobs:
  test-py39-19.2:
    docker:
      - image: circleci/python:3.9
      - *cockroach-19-2
    <<: *test-steps
    <<: *py39

  test-py39-20.1:
    docker:
      - image: circleci/python:3.9
      - *cockroach-20-1
    <<: *test-steps
    <<: *py39

  test-py39-20.2:
    docker:
      - image: circleci/python:3.9
      - *cockroach-20-2
    <<: *test-steps
    <<: *py39

  test-py39-21.1:
    docker:
      - image: circleci/python:3.9
      - *cockroach-21-1
    <<: *test-steps
    <<: *py39

  lint:
    docker:
      - image: circleci/python:3.9
    environment:
      <<: *tox-version
    steps:
      - checkout
      - run:
          name: Install testrunner
          command: pip install --user tox==${TOX_VERSION}
      - run:
          name: Lint
          command: ${HOME}/.local/bin/tox -e lint

workflows:
  version: 2
  test-and-lint:
    jobs:
      - test-py39-19.2
      - test-py39-20.1
      - test-py39-20.2
      - test-py39-21.1
      - lint
