# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cockroach/proto/config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cockroach/proto/config.proto',
  package='cockroach.proto',
  serialized_pb=_b('\n\x1c\x63ockroach/proto/config.proto\x12\x0f\x63ockroach.proto\"\x1b\n\nAttributes\x12\r\n\x05\x61ttrs\x18\x01 \x03(\t\"X\n\x07Replica\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x10\n\x08store_id\x18\x02 \x01(\x05\x12*\n\x05\x61ttrs\x18\x03 \x01(\x0b\x32\x1b.cockroach.proto.Attributes\"r\n\x0fRangeDescriptor\x12\x0f\n\x07raft_id\x18\x01 \x01(\x03\x12\x11\n\tstart_key\x18\x02 \x01(\x0c\x12\x0f\n\x07\x65nd_key\x18\x03 \x01(\x0c\x12*\n\x08replicas\x18\x04 \x03(\x0b\x32\x18.cockroach.proto.Replica\"\x1f\n\x08GCPolicy\x12\x13\n\x0bttl_seconds\x18\x01 \x01(\x05\" \n\nAcctConfig\x12\x12\n\ncluster_id\x18\x01 \x01(\t\")\n\nPermConfig\x12\x0c\n\x04read\x18\x01 \x03(\t\x12\r\n\x05write\x18\x02 \x03(\t\"\x99\x01\n\nZoneConfig\x12\x32\n\rreplica_attrs\x18\x01 \x03(\x0b\x32\x1b.cockroach.proto.Attributes\x12\x17\n\x0frange_min_bytes\x18\x02 \x01(\x03\x12\x17\n\x0frange_max_bytes\x18\x03 \x01(\x03\x12%\n\x02gc\x18\x04 \x01(\x0b\x32\x19.cockroach.proto.GCPolicyB\x07Z\x05proto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ATTRIBUTES = _descriptor.Descriptor(
  name='Attributes',
  full_name='cockroach.proto.Attributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attrs', full_name='cockroach.proto.Attributes.attrs', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=76,
)


_REPLICA = _descriptor.Descriptor(
  name='Replica',
  full_name='cockroach.proto.Replica',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='cockroach.proto.Replica.node_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='store_id', full_name='cockroach.proto.Replica.store_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attrs', full_name='cockroach.proto.Replica.attrs', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=166,
)


_RANGEDESCRIPTOR = _descriptor.Descriptor(
  name='RangeDescriptor',
  full_name='cockroach.proto.RangeDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raft_id', full_name='cockroach.proto.RangeDescriptor.raft_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_key', full_name='cockroach.proto.RangeDescriptor.start_key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_key', full_name='cockroach.proto.RangeDescriptor.end_key', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='replicas', full_name='cockroach.proto.RangeDescriptor.replicas', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=282,
)


_GCPOLICY = _descriptor.Descriptor(
  name='GCPolicy',
  full_name='cockroach.proto.GCPolicy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ttl_seconds', full_name='cockroach.proto.GCPolicy.ttl_seconds', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=315,
)


_ACCTCONFIG = _descriptor.Descriptor(
  name='AcctConfig',
  full_name='cockroach.proto.AcctConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster_id', full_name='cockroach.proto.AcctConfig.cluster_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=349,
)


_PERMCONFIG = _descriptor.Descriptor(
  name='PermConfig',
  full_name='cockroach.proto.PermConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='read', full_name='cockroach.proto.PermConfig.read', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='write', full_name='cockroach.proto.PermConfig.write', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=392,
)


_ZONECONFIG = _descriptor.Descriptor(
  name='ZoneConfig',
  full_name='cockroach.proto.ZoneConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='replica_attrs', full_name='cockroach.proto.ZoneConfig.replica_attrs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='range_min_bytes', full_name='cockroach.proto.ZoneConfig.range_min_bytes', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='range_max_bytes', full_name='cockroach.proto.ZoneConfig.range_max_bytes', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gc', full_name='cockroach.proto.ZoneConfig.gc', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=548,
)

_REPLICA.fields_by_name['attrs'].message_type = _ATTRIBUTES
_RANGEDESCRIPTOR.fields_by_name['replicas'].message_type = _REPLICA
_ZONECONFIG.fields_by_name['replica_attrs'].message_type = _ATTRIBUTES
_ZONECONFIG.fields_by_name['gc'].message_type = _GCPOLICY
DESCRIPTOR.message_types_by_name['Attributes'] = _ATTRIBUTES
DESCRIPTOR.message_types_by_name['Replica'] = _REPLICA
DESCRIPTOR.message_types_by_name['RangeDescriptor'] = _RANGEDESCRIPTOR
DESCRIPTOR.message_types_by_name['GCPolicy'] = _GCPOLICY
DESCRIPTOR.message_types_by_name['AcctConfig'] = _ACCTCONFIG
DESCRIPTOR.message_types_by_name['PermConfig'] = _PERMCONFIG
DESCRIPTOR.message_types_by_name['ZoneConfig'] = _ZONECONFIG

Attributes = _reflection.GeneratedProtocolMessageType('Attributes', (_message.Message,), dict(
  DESCRIPTOR = _ATTRIBUTES,
  __module__ = 'cockroach.proto.config_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.proto.Attributes)
  ))
_sym_db.RegisterMessage(Attributes)

Replica = _reflection.GeneratedProtocolMessageType('Replica', (_message.Message,), dict(
  DESCRIPTOR = _REPLICA,
  __module__ = 'cockroach.proto.config_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.proto.Replica)
  ))
_sym_db.RegisterMessage(Replica)

RangeDescriptor = _reflection.GeneratedProtocolMessageType('RangeDescriptor', (_message.Message,), dict(
  DESCRIPTOR = _RANGEDESCRIPTOR,
  __module__ = 'cockroach.proto.config_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.proto.RangeDescriptor)
  ))
_sym_db.RegisterMessage(RangeDescriptor)

GCPolicy = _reflection.GeneratedProtocolMessageType('GCPolicy', (_message.Message,), dict(
  DESCRIPTOR = _GCPOLICY,
  __module__ = 'cockroach.proto.config_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.proto.GCPolicy)
  ))
_sym_db.RegisterMessage(GCPolicy)

AcctConfig = _reflection.GeneratedProtocolMessageType('AcctConfig', (_message.Message,), dict(
  DESCRIPTOR = _ACCTCONFIG,
  __module__ = 'cockroach.proto.config_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.proto.AcctConfig)
  ))
_sym_db.RegisterMessage(AcctConfig)

PermConfig = _reflection.GeneratedProtocolMessageType('PermConfig', (_message.Message,), dict(
  DESCRIPTOR = _PERMCONFIG,
  __module__ = 'cockroach.proto.config_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.proto.PermConfig)
  ))
_sym_db.RegisterMessage(PermConfig)

ZoneConfig = _reflection.GeneratedProtocolMessageType('ZoneConfig', (_message.Message,), dict(
  DESCRIPTOR = _ZONECONFIG,
  __module__ = 'cockroach.proto.config_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.proto.ZoneConfig)
  ))
_sym_db.RegisterMessage(ZoneConfig)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\005proto'))
# @@protoc_insertion_point(module_scope)
