# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cockroach/proto/gossip.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cockroach.proto.config_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cockroach/proto/gossip.proto',
  package='cockroach.proto',
  serialized_pb=_b('\n\x1c\x63ockroach/proto/gossip.proto\x12\x0f\x63ockroach.proto\x1a\x1c\x63ockroach/proto/config.proto\"\x8c\x01\n\rGossipRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12#\n\x04\x61\x64\x64r\x18\x02 \x01(\x0b\x32\x15.cockroach.proto.Addr\x12%\n\x06l_addr\x18\x03 \x01(\x0b\x32\x15.cockroach.proto.Addr\x12\x0f\n\x07max_seq\x18\x04 \x01(\x03\x12\r\n\x05\x64\x65lta\x18\x05 \x01(\x0c\"I\n\x0eGossipResponse\x12\r\n\x05\x64\x65lta\x18\x01 \x01(\x0c\x12(\n\talternate\x18\x02 \x01(\x0b\x32\x15.cockroach.proto.AddrB\x07Z\x05proto')
  ,
  dependencies=[cockroach.proto.config_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GOSSIPREQUEST = _descriptor.Descriptor(
  name='GossipRequest',
  full_name='cockroach.proto.GossipRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='cockroach.proto.GossipRequest.node_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='addr', full_name='cockroach.proto.GossipRequest.addr', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l_addr', full_name='cockroach.proto.GossipRequest.l_addr', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_seq', full_name='cockroach.proto.GossipRequest.max_seq', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delta', full_name='cockroach.proto.GossipRequest.delta', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=220,
)


_GOSSIPRESPONSE = _descriptor.Descriptor(
  name='GossipResponse',
  full_name='cockroach.proto.GossipResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='delta', full_name='cockroach.proto.GossipResponse.delta', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alternate', full_name='cockroach.proto.GossipResponse.alternate', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=295,
)

_GOSSIPREQUEST.fields_by_name['addr'].message_type = cockroach.proto.config_pb2._ADDR
_GOSSIPREQUEST.fields_by_name['l_addr'].message_type = cockroach.proto.config_pb2._ADDR
_GOSSIPRESPONSE.fields_by_name['alternate'].message_type = cockroach.proto.config_pb2._ADDR
DESCRIPTOR.message_types_by_name['GossipRequest'] = _GOSSIPREQUEST
DESCRIPTOR.message_types_by_name['GossipResponse'] = _GOSSIPRESPONSE

GossipRequest = _reflection.GeneratedProtocolMessageType('GossipRequest', (_message.Message,), dict(
  DESCRIPTOR = _GOSSIPREQUEST,
  __module__ = 'cockroach.proto.gossip_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.proto.GossipRequest)
  ))
_sym_db.RegisterMessage(GossipRequest)

GossipResponse = _reflection.GeneratedProtocolMessageType('GossipResponse', (_message.Message,), dict(
  DESCRIPTOR = _GOSSIPRESPONSE,
  __module__ = 'cockroach.proto.gossip_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.proto.GossipResponse)
  ))
_sym_db.RegisterMessage(GossipResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\005proto'))
# @@protoc_insertion_point(module_scope)
