# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cockroach/proto/heartbeat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cockroach/proto/heartbeat.proto',
  package='cockroach.proto',
  serialized_pb=_b('\n\x1f\x63ockroach/proto/heartbeat.proto\x12\x0f\x63ockroach.proto\"H\n\x0cRemoteOffset\x12\x0e\n\x06offset\x18\x01 \x01(\x03\x12\x13\n\x0buncertainty\x18\x02 \x01(\x03\x12\x13\n\x0bmeasured_at\x18\x03 \x01(\x03\"X\n\x0bPingRequest\x12\x0c\n\x04ping\x18\x01 \x01(\t\x12-\n\x06offset\x18\x02 \x01(\x0b\x32\x1d.cockroach.proto.RemoteOffset\x12\x0c\n\x04\x61\x64\x64r\x18\x03 \x01(\t\"1\n\x0cPingResponse\x12\x0c\n\x04pong\x18\x01 \x01(\t\x12\x13\n\x0bserver_time\x18\x02 \x01(\x03\x42\x07Z\x05proto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REMOTEOFFSET = _descriptor.Descriptor(
  name='RemoteOffset',
  full_name='cockroach.proto.RemoteOffset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='cockroach.proto.RemoteOffset.offset', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uncertainty', full_name='cockroach.proto.RemoteOffset.uncertainty', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='measured_at', full_name='cockroach.proto.RemoteOffset.measured_at', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=124,
)


_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='cockroach.proto.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ping', full_name='cockroach.proto.PingRequest.ping', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset', full_name='cockroach.proto.PingRequest.offset', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='addr', full_name='cockroach.proto.PingRequest.addr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=214,
)


_PINGRESPONSE = _descriptor.Descriptor(
  name='PingResponse',
  full_name='cockroach.proto.PingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pong', full_name='cockroach.proto.PingResponse.pong', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_time', full_name='cockroach.proto.PingResponse.server_time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=265,
)

_PINGREQUEST.fields_by_name['offset'].message_type = _REMOTEOFFSET
DESCRIPTOR.message_types_by_name['RemoteOffset'] = _REMOTEOFFSET
DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PingResponse'] = _PINGRESPONSE

RemoteOffset = _reflection.GeneratedProtocolMessageType('RemoteOffset', (_message.Message,), dict(
  DESCRIPTOR = _REMOTEOFFSET,
  __module__ = 'cockroach.proto.heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.proto.RemoteOffset)
  ))
_sym_db.RegisterMessage(RemoteOffset)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), dict(
  DESCRIPTOR = _PINGREQUEST,
  __module__ = 'cockroach.proto.heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.proto.PingRequest)
  ))
_sym_db.RegisterMessage(PingRequest)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), dict(
  DESCRIPTOR = _PINGRESPONSE,
  __module__ = 'cockroach.proto.heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.proto.PingResponse)
  ))
_sym_db.RegisterMessage(PingResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\005proto'))
# @@protoc_insertion_point(module_scope)
