# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cockroach/proto/log.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cockroach/proto/log.proto',
  package='cockroach.proto',
  serialized_pb=_b('\n\x19\x63ockroach/proto/log.proto\x12\x0f\x63ockroach.proto\"\xa7\x02\n\x08LogEntry\x12\x10\n\x08severity\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\x03\x12\x11\n\tthread_id\x18\x03 \x01(\x05\x12\x0c\n\x04\x66ile\x18\x04 \x01(\t\x12\x0c\n\x04line\x18\x05 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x06 \x01(\t\x12+\n\x04\x61rgs\x18\x07 \x03(\x0b\x32\x1d.cockroach.proto.LogEntry.Arg\x12\x0f\n\x07node_id\x18\x08 \x01(\x05\x12\x10\n\x08store_id\x18\t \x01(\x05\x12\x0f\n\x07raft_id\x18\n \x01(\x03\x12\x0e\n\x06method\x18\x0b \x01(\x05\x12\x0b\n\x03key\x18\x0c \x01(\x0c\x12\x0e\n\x06stacks\x18\r \x01(\x0c\x1a.\n\x03\x41rg\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0b\n\x03str\x18\x02 \x01(\t\x12\x0c\n\x04json\x18\x03 \x01(\x0c\x42\x07Z\x05proto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOGENTRY_ARG = _descriptor.Descriptor(
  name='Arg',
  full_name='cockroach.proto.LogEntry.Arg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='cockroach.proto.LogEntry.Arg.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='str', full_name='cockroach.proto.LogEntry.Arg.str', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='json', full_name='cockroach.proto.LogEntry.Arg.json', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=342,
)

_LOGENTRY = _descriptor.Descriptor(
  name='LogEntry',
  full_name='cockroach.proto.LogEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='severity', full_name='cockroach.proto.LogEntry.severity', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='cockroach.proto.LogEntry.time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thread_id', full_name='cockroach.proto.LogEntry.thread_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file', full_name='cockroach.proto.LogEntry.file', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='line', full_name='cockroach.proto.LogEntry.line', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='format', full_name='cockroach.proto.LogEntry.format', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='args', full_name='cockroach.proto.LogEntry.args', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='cockroach.proto.LogEntry.node_id', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='store_id', full_name='cockroach.proto.LogEntry.store_id', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='raft_id', full_name='cockroach.proto.LogEntry.raft_id', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='method', full_name='cockroach.proto.LogEntry.method', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='cockroach.proto.LogEntry.key', index=11,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stacks', full_name='cockroach.proto.LogEntry.stacks', index=12,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LOGENTRY_ARG, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=342,
)

_LOGENTRY_ARG.containing_type = _LOGENTRY
_LOGENTRY.fields_by_name['args'].message_type = _LOGENTRY_ARG
DESCRIPTOR.message_types_by_name['LogEntry'] = _LOGENTRY

LogEntry = _reflection.GeneratedProtocolMessageType('LogEntry', (_message.Message,), dict(

  Arg = _reflection.GeneratedProtocolMessageType('Arg', (_message.Message,), dict(
    DESCRIPTOR = _LOGENTRY_ARG,
    __module__ = 'cockroach.proto.log_pb2'
    # @@protoc_insertion_point(class_scope:cockroach.proto.LogEntry.Arg)
    ))
  ,
  DESCRIPTOR = _LOGENTRY,
  __module__ = 'cockroach.proto.log_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.proto.LogEntry)
  ))
_sym_db.RegisterMessage(LogEntry)
_sym_db.RegisterMessage(LogEntry.Arg)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\005proto'))
# @@protoc_insertion_point(module_scope)
