# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cockroach/proto/timeseries.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cockroach/proto/timeseries.proto',
  package='cockroach.proto',
  serialized_pb=_b('\n cockroach/proto/timeseries.proto\x12\x0f\x63ockroach.proto\"=\n\x13TimeSeriesDatapoint\x12\x17\n\x0ftimestamp_nanos\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x01\"h\n\x0eTimeSeriesData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x38\n\ndatapoints\x18\x03 \x03(\x0b\x32$.cockroach.proto.TimeSeriesDatapoint\"\x97\x01\n\x16TimeSeriesQueryRequest\x12\x13\n\x0bstart_nanos\x18\x01 \x01(\x03\x12\x11\n\tend_nanos\x18\x02 \x01(\x03\x12>\n\x07queries\x18\x03 \x03(\x0b\x32-.cockroach.proto.TimeSeriesQueryRequest.Query\x1a\x15\n\x05Query\x12\x0c\n\x04name\x18\x01 \x01(\t\"\xbe\x01\n\x17TimeSeriesQueryResponse\x12@\n\x07results\x18\x01 \x03(\x0b\x32/.cockroach.proto.TimeSeriesQueryResponse.Result\x1a\x61\n\x06Result\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07sources\x18\x02 \x03(\t\x12\x38\n\ndatapoints\x18\x03 \x03(\x0b\x32$.cockroach.proto.TimeSeriesDatapointB\x07Z\x05proto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TIMESERIESDATAPOINT = _descriptor.Descriptor(
  name='TimeSeriesDatapoint',
  full_name='cockroach.proto.TimeSeriesDatapoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp_nanos', full_name='cockroach.proto.TimeSeriesDatapoint.timestamp_nanos', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='cockroach.proto.TimeSeriesDatapoint.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=114,
)


_TIMESERIESDATA = _descriptor.Descriptor(
  name='TimeSeriesData',
  full_name='cockroach.proto.TimeSeriesData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cockroach.proto.TimeSeriesData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='cockroach.proto.TimeSeriesData.source', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datapoints', full_name='cockroach.proto.TimeSeriesData.datapoints', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=220,
)


_TIMESERIESQUERYREQUEST_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='cockroach.proto.TimeSeriesQueryRequest.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cockroach.proto.TimeSeriesQueryRequest.Query.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=374,
)

_TIMESERIESQUERYREQUEST = _descriptor.Descriptor(
  name='TimeSeriesQueryRequest',
  full_name='cockroach.proto.TimeSeriesQueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_nanos', full_name='cockroach.proto.TimeSeriesQueryRequest.start_nanos', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_nanos', full_name='cockroach.proto.TimeSeriesQueryRequest.end_nanos', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='queries', full_name='cockroach.proto.TimeSeriesQueryRequest.queries', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TIMESERIESQUERYREQUEST_QUERY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=374,
)


_TIMESERIESQUERYRESPONSE_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='cockroach.proto.TimeSeriesQueryResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cockroach.proto.TimeSeriesQueryResponse.Result.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sources', full_name='cockroach.proto.TimeSeriesQueryResponse.Result.sources', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datapoints', full_name='cockroach.proto.TimeSeriesQueryResponse.Result.datapoints', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=470,
  serialized_end=567,
)

_TIMESERIESQUERYRESPONSE = _descriptor.Descriptor(
  name='TimeSeriesQueryResponse',
  full_name='cockroach.proto.TimeSeriesQueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='cockroach.proto.TimeSeriesQueryResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TIMESERIESQUERYRESPONSE_RESULT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=567,
)

_TIMESERIESDATA.fields_by_name['datapoints'].message_type = _TIMESERIESDATAPOINT
_TIMESERIESQUERYREQUEST_QUERY.containing_type = _TIMESERIESQUERYREQUEST
_TIMESERIESQUERYREQUEST.fields_by_name['queries'].message_type = _TIMESERIESQUERYREQUEST_QUERY
_TIMESERIESQUERYRESPONSE_RESULT.fields_by_name['datapoints'].message_type = _TIMESERIESDATAPOINT
_TIMESERIESQUERYRESPONSE_RESULT.containing_type = _TIMESERIESQUERYRESPONSE
_TIMESERIESQUERYRESPONSE.fields_by_name['results'].message_type = _TIMESERIESQUERYRESPONSE_RESULT
DESCRIPTOR.message_types_by_name['TimeSeriesDatapoint'] = _TIMESERIESDATAPOINT
DESCRIPTOR.message_types_by_name['TimeSeriesData'] = _TIMESERIESDATA
DESCRIPTOR.message_types_by_name['TimeSeriesQueryRequest'] = _TIMESERIESQUERYREQUEST
DESCRIPTOR.message_types_by_name['TimeSeriesQueryResponse'] = _TIMESERIESQUERYRESPONSE

TimeSeriesDatapoint = _reflection.GeneratedProtocolMessageType('TimeSeriesDatapoint', (_message.Message,), dict(
  DESCRIPTOR = _TIMESERIESDATAPOINT,
  __module__ = 'cockroach.proto.timeseries_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.proto.TimeSeriesDatapoint)
  ))
_sym_db.RegisterMessage(TimeSeriesDatapoint)

TimeSeriesData = _reflection.GeneratedProtocolMessageType('TimeSeriesData', (_message.Message,), dict(
  DESCRIPTOR = _TIMESERIESDATA,
  __module__ = 'cockroach.proto.timeseries_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.proto.TimeSeriesData)
  ))
_sym_db.RegisterMessage(TimeSeriesData)

TimeSeriesQueryRequest = _reflection.GeneratedProtocolMessageType('TimeSeriesQueryRequest', (_message.Message,), dict(

  Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), dict(
    DESCRIPTOR = _TIMESERIESQUERYREQUEST_QUERY,
    __module__ = 'cockroach.proto.timeseries_pb2'
    # @@protoc_insertion_point(class_scope:cockroach.proto.TimeSeriesQueryRequest.Query)
    ))
  ,
  DESCRIPTOR = _TIMESERIESQUERYREQUEST,
  __module__ = 'cockroach.proto.timeseries_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.proto.TimeSeriesQueryRequest)
  ))
_sym_db.RegisterMessage(TimeSeriesQueryRequest)
_sym_db.RegisterMessage(TimeSeriesQueryRequest.Query)

TimeSeriesQueryResponse = _reflection.GeneratedProtocolMessageType('TimeSeriesQueryResponse', (_message.Message,), dict(

  Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
    DESCRIPTOR = _TIMESERIESQUERYRESPONSE_RESULT,
    __module__ = 'cockroach.proto.timeseries_pb2'
    # @@protoc_insertion_point(class_scope:cockroach.proto.TimeSeriesQueryResponse.Result)
    ))
  ,
  DESCRIPTOR = _TIMESERIESQUERYRESPONSE,
  __module__ = 'cockroach.proto.timeseries_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.proto.TimeSeriesQueryResponse)
  ))
_sym_db.RegisterMessage(TimeSeriesQueryResponse)
_sym_db.RegisterMessage(TimeSeriesQueryResponse.Result)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\005proto'))
# @@protoc_insertion_point(module_scope)
