# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cockroach/sql/driver/wire.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cockroach/sql/driver/wire.proto',
  package='cockroach.sql.driver',
  serialized_pb=_b('\n\x1f\x63ockroach/sql/driver/wire.proto\x12\x14\x63ockroach.sql.driver\"\xaf\x02\n\x05\x44\x61tum\x12\x12\n\x08\x62ool_val\x18\x01 \x01(\x08H\x00\x12\x11\n\x07int_val\x18\x02 \x01(\x03H\x00\x12\x13\n\tfloat_val\x18\x03 \x01(\x01H\x00\x12\x13\n\tbytes_val\x18\x04 \x01(\x0cH\x00\x12\x14\n\nstring_val\x18\x05 \x01(\tH\x00\x12\x39\n\x08\x64\x61te_val\x18\x06 \x01(\x0b\x32%.cockroach.sql.driver.Datum.TimestampH\x00\x12\x39\n\x08time_val\x18\x07 \x01(\x0b\x32%.cockroach.sql.driver.Datum.TimestampH\x00\x12\x16\n\x0cinterval_val\x18\x08 \x01(\x03H\x00\x1a&\n\tTimestamp\x12\x0b\n\x03sec\x18\x01 \x01(\x03\x12\x0c\n\x04nsec\x18\x02 \x01(\rB\t\n\x07payload\"b\n\x07Request\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07session\x18\x02 \x01(\x0c\x12\x0b\n\x03sql\x18\x03 \x01(\t\x12+\n\x06params\x18\x04 \x03(\x0b\x32\x1b.cockroach.sql.driver.Datum\"\x98\x03\n\x08Response\x12\x0f\n\x07session\x18\x01 \x01(\x0c\x12\x36\n\x07results\x18\x02 \x03(\x0b\x32%.cockroach.sql.driver.Response.Result\x1a\xc2\x02\n\x06Result\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x38\n\x03\x64\x64l\x18\x02 \x01(\x0b\x32).cockroach.sql.driver.Response.Result.DDLH\x00\x12\x17\n\rrows_affected\x18\x03 \x01(\rH\x00\x12:\n\x04rows\x18\x04 \x01(\x0b\x32*.cockroach.sql.driver.Response.Result.RowsH\x00\x1a\x05\n\x03\x44\x44L\x1a\x89\x01\n\x04Rows\x12\x0f\n\x07\x63olumns\x18\x01 \x03(\t\x12<\n\x04rows\x18\x02 \x03(\x0b\x32..cockroach.sql.driver.Response.Result.Rows.Row\x1a\x32\n\x03Row\x12+\n\x06values\x18\x01 \x03(\x0b\x32\x1b.cockroach.sql.driver.DatumB\x07\n\x05unionB\x08Z\x06\x64river')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DATUM_TIMESTAMP = _descriptor.Descriptor(
  name='Timestamp',
  full_name='cockroach.sql.driver.Datum.Timestamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sec', full_name='cockroach.sql.driver.Datum.Timestamp.sec', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nsec', full_name='cockroach.sql.driver.Datum.Timestamp.nsec', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=350,
)

_DATUM = _descriptor.Descriptor(
  name='Datum',
  full_name='cockroach.sql.driver.Datum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bool_val', full_name='cockroach.sql.driver.Datum.bool_val', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int_val', full_name='cockroach.sql.driver.Datum.int_val', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_val', full_name='cockroach.sql.driver.Datum.float_val', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytes_val', full_name='cockroach.sql.driver.Datum.bytes_val', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='string_val', full_name='cockroach.sql.driver.Datum.string_val', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date_val', full_name='cockroach.sql.driver.Datum.date_val', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_val', full_name='cockroach.sql.driver.Datum.time_val', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interval_val', full_name='cockroach.sql.driver.Datum.interval_val', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATUM_TIMESTAMP, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='cockroach.sql.driver.Datum.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=58,
  serialized_end=361,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='cockroach.sql.driver.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='cockroach.sql.driver.Request.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session', full_name='cockroach.sql.driver.Request.session', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sql', full_name='cockroach.sql.driver.Request.sql', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='cockroach.sql.driver.Request.params', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=461,
)


_RESPONSE_RESULT_DDL = _descriptor.Descriptor(
  name='DDL',
  full_name='cockroach.sql.driver.Response.Result.DDL',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=718,
  serialized_end=723,
)

_RESPONSE_RESULT_ROWS_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='cockroach.sql.driver.Response.Result.Rows.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='cockroach.sql.driver.Response.Result.Rows.Row.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=813,
  serialized_end=863,
)

_RESPONSE_RESULT_ROWS = _descriptor.Descriptor(
  name='Rows',
  full_name='cockroach.sql.driver.Response.Result.Rows',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='columns', full_name='cockroach.sql.driver.Response.Result.Rows.columns', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rows', full_name='cockroach.sql.driver.Response.Result.Rows.rows', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RESPONSE_RESULT_ROWS_ROW, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=726,
  serialized_end=863,
)

_RESPONSE_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='cockroach.sql.driver.Response.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='cockroach.sql.driver.Response.Result.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ddl', full_name='cockroach.sql.driver.Response.Result.ddl', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rows_affected', full_name='cockroach.sql.driver.Response.Result.rows_affected', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rows', full_name='cockroach.sql.driver.Response.Result.rows', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RESPONSE_RESULT_DDL, _RESPONSE_RESULT_ROWS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='union', full_name='cockroach.sql.driver.Response.Result.union',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=550,
  serialized_end=872,
)

_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='cockroach.sql.driver.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='cockroach.sql.driver.Response.session', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='results', full_name='cockroach.sql.driver.Response.results', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RESPONSE_RESULT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=872,
)

_DATUM_TIMESTAMP.containing_type = _DATUM
_DATUM.fields_by_name['date_val'].message_type = _DATUM_TIMESTAMP
_DATUM.fields_by_name['time_val'].message_type = _DATUM_TIMESTAMP
_DATUM.oneofs_by_name['payload'].fields.append(
  _DATUM.fields_by_name['bool_val'])
_DATUM.fields_by_name['bool_val'].containing_oneof = _DATUM.oneofs_by_name['payload']
_DATUM.oneofs_by_name['payload'].fields.append(
  _DATUM.fields_by_name['int_val'])
_DATUM.fields_by_name['int_val'].containing_oneof = _DATUM.oneofs_by_name['payload']
_DATUM.oneofs_by_name['payload'].fields.append(
  _DATUM.fields_by_name['float_val'])
_DATUM.fields_by_name['float_val'].containing_oneof = _DATUM.oneofs_by_name['payload']
_DATUM.oneofs_by_name['payload'].fields.append(
  _DATUM.fields_by_name['bytes_val'])
_DATUM.fields_by_name['bytes_val'].containing_oneof = _DATUM.oneofs_by_name['payload']
_DATUM.oneofs_by_name['payload'].fields.append(
  _DATUM.fields_by_name['string_val'])
_DATUM.fields_by_name['string_val'].containing_oneof = _DATUM.oneofs_by_name['payload']
_DATUM.oneofs_by_name['payload'].fields.append(
  _DATUM.fields_by_name['date_val'])
_DATUM.fields_by_name['date_val'].containing_oneof = _DATUM.oneofs_by_name['payload']
_DATUM.oneofs_by_name['payload'].fields.append(
  _DATUM.fields_by_name['time_val'])
_DATUM.fields_by_name['time_val'].containing_oneof = _DATUM.oneofs_by_name['payload']
_DATUM.oneofs_by_name['payload'].fields.append(
  _DATUM.fields_by_name['interval_val'])
_DATUM.fields_by_name['interval_val'].containing_oneof = _DATUM.oneofs_by_name['payload']
_REQUEST.fields_by_name['params'].message_type = _DATUM
_RESPONSE_RESULT_DDL.containing_type = _RESPONSE_RESULT
_RESPONSE_RESULT_ROWS_ROW.fields_by_name['values'].message_type = _DATUM
_RESPONSE_RESULT_ROWS_ROW.containing_type = _RESPONSE_RESULT_ROWS
_RESPONSE_RESULT_ROWS.fields_by_name['rows'].message_type = _RESPONSE_RESULT_ROWS_ROW
_RESPONSE_RESULT_ROWS.containing_type = _RESPONSE_RESULT
_RESPONSE_RESULT.fields_by_name['ddl'].message_type = _RESPONSE_RESULT_DDL
_RESPONSE_RESULT.fields_by_name['rows'].message_type = _RESPONSE_RESULT_ROWS
_RESPONSE_RESULT.containing_type = _RESPONSE
_RESPONSE_RESULT.oneofs_by_name['union'].fields.append(
  _RESPONSE_RESULT.fields_by_name['ddl'])
_RESPONSE_RESULT.fields_by_name['ddl'].containing_oneof = _RESPONSE_RESULT.oneofs_by_name['union']
_RESPONSE_RESULT.oneofs_by_name['union'].fields.append(
  _RESPONSE_RESULT.fields_by_name['rows_affected'])
_RESPONSE_RESULT.fields_by_name['rows_affected'].containing_oneof = _RESPONSE_RESULT.oneofs_by_name['union']
_RESPONSE_RESULT.oneofs_by_name['union'].fields.append(
  _RESPONSE_RESULT.fields_by_name['rows'])
_RESPONSE_RESULT.fields_by_name['rows'].containing_oneof = _RESPONSE_RESULT.oneofs_by_name['union']
_RESPONSE.fields_by_name['results'].message_type = _RESPONSE_RESULT
DESCRIPTOR.message_types_by_name['Datum'] = _DATUM
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

Datum = _reflection.GeneratedProtocolMessageType('Datum', (_message.Message,), dict(

  Timestamp = _reflection.GeneratedProtocolMessageType('Timestamp', (_message.Message,), dict(
    DESCRIPTOR = _DATUM_TIMESTAMP,
    __module__ = 'cockroach.sql.driver.wire_pb2'
    # @@protoc_insertion_point(class_scope:cockroach.sql.driver.Datum.Timestamp)
    ))
  ,
  DESCRIPTOR = _DATUM,
  __module__ = 'cockroach.sql.driver.wire_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.sql.driver.Datum)
  ))
_sym_db.RegisterMessage(Datum)
_sym_db.RegisterMessage(Datum.Timestamp)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'cockroach.sql.driver.wire_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.sql.driver.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(

  Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(

    DDL = _reflection.GeneratedProtocolMessageType('DDL', (_message.Message,), dict(
      DESCRIPTOR = _RESPONSE_RESULT_DDL,
      __module__ = 'cockroach.sql.driver.wire_pb2'
      # @@protoc_insertion_point(class_scope:cockroach.sql.driver.Response.Result.DDL)
      ))
    ,

    Rows = _reflection.GeneratedProtocolMessageType('Rows', (_message.Message,), dict(

      Row = _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), dict(
        DESCRIPTOR = _RESPONSE_RESULT_ROWS_ROW,
        __module__ = 'cockroach.sql.driver.wire_pb2'
        # @@protoc_insertion_point(class_scope:cockroach.sql.driver.Response.Result.Rows.Row)
        ))
      ,
      DESCRIPTOR = _RESPONSE_RESULT_ROWS,
      __module__ = 'cockroach.sql.driver.wire_pb2'
      # @@protoc_insertion_point(class_scope:cockroach.sql.driver.Response.Result.Rows)
      ))
    ,
    DESCRIPTOR = _RESPONSE_RESULT,
    __module__ = 'cockroach.sql.driver.wire_pb2'
    # @@protoc_insertion_point(class_scope:cockroach.sql.driver.Response.Result)
    ))
  ,
  DESCRIPTOR = _RESPONSE,
  __module__ = 'cockroach.sql.driver.wire_pb2'
  # @@protoc_insertion_point(class_scope:cockroach.sql.driver.Response)
  ))
_sym_db.RegisterMessage(Response)
_sym_db.RegisterMessage(Response.Result)
_sym_db.RegisterMessage(Response.Result.DDL)
_sym_db.RegisterMessage(Response.Result.Rows)
_sym_db.RegisterMessage(Response.Result.Rows.Row)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\006driver'))
# @@protoc_insertion_point(module_scope)
